// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoj2Rc_owWixelgCmhKXlM67o2jPWKjXM',
    appId: '1:793738107822:android:cca676be4177056ae1863f',
    messagingSenderId: '793738107822',
    projectId: 'iwealth-by-norrenberger',
    storageBucket: 'iwealth-by-norrenberger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TLorW1xqteJPr97TqmNd_-aTfacC7tQ',
    appId: '1:793738107822:ios:790b414c1d727e99e1863f',
    messagingSenderId: '793738107822',
    projectId: 'iwealth-by-norrenberger',
    storageBucket: 'iwealth-by-norrenberger.appspot.com',
    androidClientId: '793738107822-to57r3v38dbo40m8575bbcecsgrjhpvi.apps.googleusercontent.com',
    iosClientId: '793738107822-guf7ml4gu6hu1faku24pvmgh550e74a5.apps.googleusercontent.com',
    iosBundleId: 'com.iwealth.app',
  );
}
